version: "3.1"
networks:
  library_network:
    driver: bridge

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3309:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    networks:
      - library_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - library_network
    links:
      - mysql-db

  library:
    image: irynakos/school-library:latest
    container_name: library
    command: bash -c 'while !</dev/tcp/mysql-db/3306; do sleep 1; done; npm start'
    ports:
      - 3000:3000
    networks:
      - library_network
    env_file:
      - .env
    depends_on:
      - mysql-db
      - phpmyadmin
    environment:
      MYSQL_DATABASE_HOST: ${MYSQL_DATABASE_HOST}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PORT: '3306'
    restart: always

volumes:
  myapp:
